apiVersion: v1
kind: Template
metadata:
  name: quarkus-registry
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: quarkus-registry
    spec:
      replicas: ${{REPLICAS}}
      selector:
        service: quarkus-registry
      strategy:
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            service: quarkus-registry
        spec:
          serviceAccount: ${SERVICE_ACCOUNT}
          serviceAccountName: ${SERVICE_ACCOUNT}
          containers:
            - image: ${IMAGE}:${IMAGE_TAG}
              imagePullPolicy: Always
              name: quarkus-registry-app
              ports:
                - containerPort: 8080
              livenessProbe:
                httpGet:
                  path: /q/health/live
                  port: 8080
                initialDelaySeconds: 15
                periodSeconds: 10
                timeoutSeconds: 3
              readinessProbe:
                httpGet:
                  path: /q/health/ready
                  port: 8080
                initialDelaySeconds: 15
                periodSeconds: 10
                timeoutSeconds: 3
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              envFrom:
                - configMapRef:
                    name: registry-quarkus
              env:
                - name: QUARKUS_DATASOURCE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: registry-quarkus-redhat-rds
                      key: db.user
                - name: QUARKUS_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: registry-quarkus-redhat-rds
                      key: db.password
                - name: TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: access-token
                - name: QUARKUS_LOG_SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: sentry-dsn
                      optional: true
      triggers:
        - type: ConfigChange
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        service: quarkus-registry
      name: quarkus-registry
    spec:
      ports:
        - name: '8080'
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        service: quarkus-registry
      sessionAffinity: None
      type: ClusterIP
parameters:
  - name: IMAGE
    value: quay.io/quarkus/registry-app
    required: true
  - name: IMAGE_TAG
    value: latest
    required: true
  - name: CPU_REQUEST
    required: true
    value: 400m
  - name: CPU_LIMIT
    required: true
    value: 1000m
  - name: MEMORY_REQUEST
    required: true
    value: 768Mi
  - displayName: Memory limit
    required: true
    name: MEMORY_LIMIT
    value: 1Gi
  - name: REPLICAS
    required: true
    value: '1'
  - name: SERVICE_ACCOUNT