name: Publish Docker image to Quay.io

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE.txt'
      - 'deploy-to-openshift.sh'
    branches:
      - 'main'

jobs:
  build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build
        run: |
          ./mvnw -e -B -DskipTests=true clean package -Dnative

      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: ${{ secrets.DOCKER_USERNAME }}
          # Container registry password
          password: ${{ secrets.DOCKER_PASSWORD }} 
          # Container registry server url
          login-server: quay.io

      - name: Build and push Docker images
        run: |
          IMAGE_TAG=$(git rev-parse --short=7 HEAD)
          # IMAGE_TAG=v${{ github.run_number }}
          ./mvnw package -Pnative
          docker build -f src/main/docker/Dockerfile.native -t quay.io/quarkus/registry-app:latest .
          docker tag quay.io/quarkus/registry-app:latest quay.io/quarkus/registry-app:${IMAGE_TAG}
          docker push quay.io/quarkus/registry-app:latest
          docker push quay.io/quarkus/registry-app:${IMAGE_TAG}
